# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3

    filters:
      branches:
        - only:
            - develop

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ca:93:f8:50:aa:e2:e6:52:94:97:17:2e:72:cd:27:eb"
      - run:
          name: Realiza o deploy do projeto
          command: |
            ssh-keyscan -H 45.77.73.23 >> ~/.ssh/known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git clone -b develop --single-branch git@github.com:gabrielmendanha/antifragil.git
            cd antifragil
            npm install
            npm run build
            ls
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh root@45.77.73.23 'rm -rf /root/www/*'
            scp -r /dist/antifragil/* root@45.77.73.23:/root/www/*
